ec = input("Enter emo code: ")
ec=int(ec)
en = input("Enter emp name:")
es = float(input("Enter emp Salary:"))
em = int(input("Enter emp mobile no:"))
print("Emp code: ",ec)
print("Emp name: ",en)
print("Emp salary: ",es)
print("Emp mobile no: ",em)
